version: '3.8'

services:
  selenoid:
    image: aerokube/selenoid:latest
    ports:
      - "4444:4444"
    volumes:
      - "./etc/selenoid:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./browsers.json:/etc/selenoid/browsers.json:ro"
    command: ["-conf", "/etc/selenoid/browsers.json", "-limit", "10"]

  tests:
    build: .
    depends_on:
      - selenoid
    environment:
      SELENOID_URL: "http://selenoid:4444/wd/hub"
    volumes:
      - "./allure-results:/app/allure-results:z"